apiVersion: "kafka.nais.io/v1"
kind: "Topic"
metadata:
  name: {{ topic }}
  namespace: raptus
  labels:
    team: raptus
spec:
  pool: {{ pool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: raptus
      application: dp-rapp-api
      access: read
    - team: raptus
      application: aiven-dev
      access: readwrite
